export const COMMON_SOMEACTION = "COMMON_SOMEACTION";

export const COMMON_LOADER_WAIT = "COMMON_LOADER_WAIT";
export const COMMON_LOADER_ERROR = "COMMON_LOADER_ERROR";
export const COMMON_LOADER_OK = "COMMON_LOADER_OK";

export const COMMON_AUTH_LOGOUTASYNC = "COMMON_AUTH_LOGOUTASYNC";
export const COMMON_AUTH_LOGINASYNC = "COMMON_AUTH_LOGINASYNC";
export const COMMON_AUTH_BACKTOADMINFROMANOTHERUSERASYNC = "COMMON_AUTH_BACKTOADMINFROMANOTHERUSERASYNC";
export const COMMON_AUTH_LOGINASANOTHERUSERASYNC = "COMMON_AUTH_LOGINASANOTHERUSERASYNC";
export const COMMON_AUTH_GETAUTHINFOASYNC = "COMMON_AUTH_GETAUTHINFOASYNC";

export const COMMON_AUTH_LOGIN = "COMMON_AUTH_LOGIN";
export const COMMON_AUTH_LOGOUT = "COMMON_AUTH_LOGOUT";
export const COMMON_AUTH_SETITEM = "COMMON_AUTH_SETITEM";
export const COMMON_AUTH_CLEARITEM = "COMMON_AUTH_CLEARITEM";

export const DASHBOARD_GETPRICEASYNC = "DASHBOARD_GETPRICEASYNC";
export const DASHBOARD_SETPRICE = "DASHBOARD_SETPRICE";

export const HOME_SENDMESSAGEASYNC = "HOME_SENDMESSAGEASYNC";
export const HOME_SETITEM = "HOME_SETITEM";
export const HOME_SETMESSAGES = "HOME_SETMESSAGES";
export const HOME_SETUSERS = "HOME_SETUSERS";
export const HOME_ADDMESSAGE = "HOME_ADDMESSAGE";
export const HOME_ADDUSER = "HOME_ADDUSER";